### ISSUE TITLE
Support for remote CERT paths

### ISSUE THREAD

**Issue by aronmgv** [henkelmax/traefik-mailcow-certdumper#3]
Hi,

I found myself in scenario where my Traefik and Mailcow server are on different hosts.. do you think you can implement a way to copy certs to a remote host? E.g. via `rsync` or `scp` ? So user can avoid setting up remote shares etc.. 

Another question is how to handle multiple email domains? Just configuring another container with different `DOMAIN: anotherdomain.com` ? Not sure how mailcow handles them internally - if the same folder.. or different file name ?

Thanks, Michal

**Comment by henkelmax** [comment]
> do you think you can implement a way to copy certs to a remote host? E.g. via rsync or scp ? So user can avoid setting up remote shares etc..

I don't think tis is too useful, as this whole program is not designed to work with remote hosts, as it also could not restart the mailcow containers. I would recommend using something like NFS or any other network file system to store the certificates.

> Another question is how to handle multiple email domains? Just configuring another container with different DOMAIN: anotherdomain.com ? Not sure how mailcow handles them internally - if the same folder.. or different file name ?

It's not about the email domains, its about the domain, your mail server runs on (I think).

**Comment by aronmgv** [comment]
> I don't think tis is too useful, as this whole program is not designed to work with remote hosts, as it also could not restart the mailcow containers. I would recommend using something like NFS or any other network file system to store the certificates.

Thx, makes sense. Forgot about restarting the mailcow..

> It's not about the email domains, its about the domain, your mail server runs on (I think).

Ahh, you are right - I remember now, so no problem then. 

Thanks anyway. Michal
