### ISSUE TITLE
Does it still work with the latest Mailcow?

### ISSUE THREAD

**Issue by aronmgv** [henkelmax/traefik-mailcow-certdumper#4]
Hey, sorry for this kind of approach on this problem, but it no longer works for me with the latest Mailcow. I am having expired or wrong certificate problem. Your container will correctly replace certificate and key but other email clients report certificate errors:

Authelia logs:
```
traefik2.authelia | time="2021-03-14T23:09:18+01:00" level=info msg="Logging severity set to debug"
traefik2.authelia | time="2021-03-14T23:09:18+01:00" level=debug msg="Storage schema is being checked to verify it is up to date"
traefik2.authelia | time="2021-03-14T23:09:18+01:00" level=debug msg="Storage schema is up to date"
traefik2.authelia | time="2021-03-14T23:09:18+01:00" level=debug msg="Notifier SMTP client attempting connection to mail.example.com:587"
traefik2.authelia | time="2021-03-14T23:09:18+01:00" level=debug msg="Notifier SMTP client connected successfully"
traefik2.authelia | time="2021-03-14T23:09:18+01:00" level=debug msg="Notifier SMTP server supports STARTTLS (disableVerifyCert: false, ServerName: mail.example.com), attempting"
traefik2.authelia | time="2021-03-14T23:09:18+01:00" level=warning msg="Notifier SMTP client encountered error during cleanup: x509: certificate has expired or is not yet valid: current time 2021-03-14T23:09:18+01:00 is after 2021-03-08T21:19:04Z"
traefik2.authelia | time="2021-03-14T23:09:18+01:00" level=fatal msg="Error during notifier startup check: x509: certificate has expired or is not yet valid: current time 2021-03-14T23:09:18+01:00 is after 2021-03-08T21:19:04Z" stack="github.com/authelia/authelia/cmd/authelia/main.go:112 startServer\ngithub.com/authelia/authelia/cmd/authelia/main.go:137 main.func1\ngithub.com/spf13/cobra@v1.1.3/command.go:856          (*Command).execute\ngithub.com/spf13/cobra@v1.1.3/command.go:960          (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.1.3/command.go:897          main\ngithub.com/authelia/authelia/cmd/authelia/main.go:154 main\nruntime/proc.go:225                                   main\nruntime/asm_amd64.s:1371                              goexit"
traefik2.authelia exited with code 1
```

In mailcow conf I have disabled acme (otherwise it would replace cert and key on restart).

Any idea what it might be?

Appreciate your time. Michal

**Comment by henkelmax** [comment]
This tool just watches on file changes and copies the config to the mailcow folder.
You could check if the certificate in your mailcow folder is the same as in your traefik acme json.
If it is the same, the tool still works.

**Comment by aronmgv** [comment]
Found the problem. Something had to change on the mailcow's side. Now the correct path to SSL folder should include also mail folder within ssl directory:

`/path/to/mailcow-dockerized/data/assets/ssl/mail.example.com/`

Meaning `cert.pem` and `key.pem` within `mail.example.com` are to be replaced not those within root ssl directory. My theory is that they reversed logic when copying them: now coming from `ssl/mail.example.com/` -> `ssl/`. Before it was `ssl/` -> `ssl/mail.example.com/`.

So the steps were:
1) enabled back lets_encrypt within mailcow config
2) run `./update.sh` script - that set me up with default mailcow config for SSL
3) dumped certs to `/path/to/mailcow-dockerized/data/assets/ssl/mail.example.com/`
4) run `./update.sh` again and noticed certs in root `ssl/` folder got automatically replaced by those dumped in `ssl/mail.example.com/`

You can check yourself. Thanks

**Comment by henkelmax** [comment]
Thanks for letting me know!
